# https://taskfile.dev

version: "3"

env:
  VIRTUAL_ENV:
    sh: echo `pwd`"/.venv"
  PATH:
    sh: echo `pwd`"/.venv/bin:$PATH"

tasks:
  default:
    cmd: task --list-all
      # - task: test
      # - task: lint
      # - task: build
  silent: true

  install:
    cmds:
      - uv sync --frozen

  dev:
    deps:
      - task: test:watch
      - task: fix:watch
      - task: typecheck:watch

  build:
    cmds:
      - uv build

  test:
    cmds:
      - task: pytest

  test:watch:
    deps:
      - task: pytest:watch

  lint:
    cmds:
      - task: ruff:check
      - task: ruff:format:check

  lint:watch:
    deps:
      - task: ruff:check:watch

  fix:
    cmds:
      - task: ruff:check:fix

  fix:watch:
    deps:
      - task: ruff:check:fix:watch

  fix:unsafe:
    cmds:
      - task: ruff:check:fix:unsafe

  fix:unsafe:watch:
    deps:
      - task: ruff:check:fix:unsafe:watch

  format:
    aliases: ["fmt"]
    cmds:
      - task: ruff:format

  publish:
    cmds:
      - uv publish -u __token__

  publish:dry-run:
    cmds:
      - uv publish --trusted-publishing always --index testpypi --offline

  typecheck:
    cmds:
      - task: pyright

  typecheck:watch:
    deps:
      - task: pyright:watch

  #
  # Tools
  #

  # pyright

  pyright:
    cmds:
      - uv run pyright .

  pyright:watch:
    cmds:
      - uv run pyright --watch .

  # pytest

  pytest:
    cmds:
      - uv run pytest --cov=asyncio_gevent

  pytest:watch:
    cmds:
      - uv run ptw --now --cov=asyncio_gevent .

  # ruff

  ruff:check:
    cmd: uv run ruff check

  ruff:check:watch:
    cmd: uv run ruff check --watch

  ruff:check:fix:
    cmd: uv run ruff check --fix

  ruff:check:fix:watch:
    cmd: uv run ruff check --fix --watch

  ruff:check:fix:unsafe:
    cmd: uv run ruff check --fix --unsafe-fixes

  ruff:check:fix:unsafe:watch:
    cmd: uv run ruff check --fix --unsafe-fixes --watch

  ruff:format:
    cmd: uv run ruff format

  ruff:format:check:
    cmd: uv run ruff format --check

  #
  # devcontainer commands
  #

  devcontainer:postCreateCommand:
    cmds:
      - task: install
