# https://taskfile.dev

version: "3"

env:
  VIRTUAL_ENV:
    sh: echo `pwd`"/.venv"
  PATH:
    sh: echo `pwd`"/.venv/bin:$PATH"

tasks:
  default:
    cmds:
      - task: test
      - task: lint
      - task: build
  silent: true

  install:
    cmds:
      - uv install

  test:
    cmds:
      - uv run pytest --cov=asyncio_gevent

  lint:
    cmds:
      - task: ruff
      - task: pyright

  build:
    cmds:
      - uv build

  publish:
    cmds:
      - uv publish -u __token__

  publish:dryRun:
    cmds:
      - uv publish --dry-run -u __token__ -p token

  ruff:
    cmds:
      - uv run ruff asyncio_gevent tests --fix

  pyright:
    cmds:
      - uv run pyright .

  devcontainer:postCreateCommand:
    cmds:
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install uv
      - task: install
