name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install-dependencies
      run: |
        python -m pip intall poetry
        python -m venv .venv
        poetry install
    - name: flake8
      run: |
        poetry run flake8 asyncio_gevent tests --count  --show-source --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: black
      run: |
        poetry run black --check --verbose asyncio_gevent tests
    - name: reorder-python-imports
      run: |
        poetry run reorder-python-imports --separate-from-import --separate-relative asyncio_gevent/**/*.py tests/**/*.py
    - name: mypy
      run: |
        poetry run mypy .
    - name: test
      run: |
        poetry run pytest
